services:
  db:
    image: postgres:16
    container_name: task_manager_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - task_manager_pg:/var/lib/postgresql/data

volumes:
  task_manager_pg:
